<?php

namespace Database\Seeders;

use App\Models\Murid;
use App\Models\Kelas;
use Illuminate\Database\Seeder;

class MuridSeeder extends Seeder
{
    public function run(): void
    {
        $kelas = Kelas::query()->where('kode', 'X-1')->firstOrFail();

        $siswa = [
            [
                'nama'          => 'ABI MANYAU PUTRO PRATOMO',
                'nis'           => '25.01.001',
                'nisn'          => '3102222526',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2010-01-25',
                'alamat'        => 'JL.Kapuk RT 16 RW 03 Kel. Kapuk Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'AHMAD AL GHIFARI',
                'nis'           => '25.01.002',
                'nisn'          => '0088731599',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2008-12-07',
                'alamat'        => 'KP. UTAN RT 08 RW 09 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'ALIF HANAN RAIHAN',
                'nis'           => '25.01.003',
                'nisn'          => '0092459443',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-07-22',
                'alamat'        => 'Jl. Fajar Baru Utara RT 09 RW 07 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'AUFILANA RAHMATIKA',
                'nis'           => '25.01.004',
                'nisn'          => '0096140654',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-01-22',
                'alamat'        => 'JL. BANGUN NUSA RAYA RT 13 RW 03 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'BALQIS ALMIRA THALIB',
                'nis'           => '25.01.005',
                'nisn'          => '0095176231',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Tangerang',
                'tanggal_lahir' => '2009-03-13',
                'alamat'        => 'Kp. Gaga RT 06 RW 09 Kel. Semanan Kec.Kalideres Jakarta Barat',
            ],
            [
                'nama'          => 'CIKAL OKTAVIYAN',
                'nis'           => '23.02.005',
                'nisn'          => '0045977664',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2004-11-29',
                'alamat'        => 'JL. PEDONGKELAN RT 10 RW 13 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'Dara Hijryanti Nur Suhendi',
                'nis'           => '25.01.006',
                'nisn'          => '0099593381',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Sumedang',
                'tanggal_lahir' => '2009-12-18',
                'alamat'        => 'JL. Tanjungkerta RT 02 RW 05 Kel. Citimun Kec.Cimalaka',
            ],
            [
                'nama'          => 'DIAN ANDINI',
                'nis'           => '23.01.014',
                'nisn'          => '0058585179',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2005-06-05',
                'alamat'        => 'JL. H MALI RT 11 RW 01 Kel. Duri Kosambi Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'DWI RAMADHAN',
                'nis'           => '25.01.007',
                'nisn'          => '0087447910',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2008-09-25',
                'alamat'        => 'JL. THALIB III RT.004/005 KRUKUT Kec. Taman Sari',
            ],
            [
                'nama'          => 'FAIRUZ AULIA PUTRI ANDAM',
                'nis'           => '25.01.008',
                'nisn'          => '3094442171',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-11-04',
                'alamat'        => 'KP. PANGKALAN RT 02 RW 10 Kel. Semanan Kec.Kalideres Jakarta Barat',
            ],
            [
                'nama'          => 'FICCA ALIFA ZAHRA',
                'nis'           => '25.01.009',
                'nisn'          => '98884477',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-04-21',
                'alamat'        => 'KP.Utan Bahagia RT 12 RW 07 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'FITRA AULIA RAMADHANI',
                'nis'           => '23.02.013',
                'nisn'          => '0065032797',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2006-10-18',
                'alamat'        => 'Jln.Nurul Amal VIII No.10 RT 03 RW 05 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => "GIVARIE RAYHAN MA'RUF",
                'nis'           => '22.01.013',
                'nisn'          => '0061109175',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2006-12-06',
                'alamat'        => 'Kp. Utan Bahagia No.227 RT 06 RW 04 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'ILHAM BUDIYARTO',
                'nis'           => '25.01.010',
                'nisn'          => '0093210477',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-10-03',
                'alamat'        => 'Perumnas Blok E.12/14 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'JUSUF APRILIO TOMATALA',
                'nis'           => '25.01.011',
                'nisn'          => '0103059592',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Surakarta',
                'tanggal_lahir' => '2010-04-08',
                'alamat'        => 'KAMARIAN/PASARUWEY Kel. Kamarian Kec.Kairatu',
            ],
            [
                'nama'          => 'KEYLLA PUTRI MARETHA',
                'nis'           => '25.01.012',
                'nisn'          => '0095137047',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Baturaja',
                'tanggal_lahir' => '2009-03-07',
                'alamat'        => 'Bangun Nusa Raya RT 08 RW 03 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'KEYSA RAHMAWATI',
                'nis'           => '25.01.013',
                'nisn'          => '0083629011',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2008-07-12',
                'alamat'        => 'BANGUN NUSA RAYA RT 05 RW 03 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'MAULIDYA ASHARI',
                'nis'           => '25.01.014',
                'nisn'          => '0105234245',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Tangerang',
                'tanggal_lahir' => '2010-03-14',
                'alamat'        => 'Jl. SETIA NO. 73 RT 02 RW 01 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'MUHAMMAD ARSYAD AS-SALIM',
                'nis'           => '25.01.015',
                'nisn'          => '0093103860',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-07-01',
                'alamat'        => 'JL PEDONGKELAN RT 17 RW 13 Kel.Kapuk Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'MUHAMMAD FARREL AL-JAELANI JOESUP',
                'nis'           => '25.01.016',
                'nisn'          => '0109492369',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2010-05-07',
                'alamat'        => 'KALIDERES NO. 8 RT 06 RW 01 Kel.Kalideres Kec.Kalideres Jakarta Barat',
            ],
            [
                'nama'          => 'Mustahil',
                'nis'           => '25.01.017',
                'nisn'          => '0106678161',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2010-01-08',
                'alamat'        => 'Pesing Poglar RT 06 RW 02 Kel.Kedaung Kali Angke Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'NAISHA ANANDITA',
                'nis'           => '25.01.018',
                'nisn'          => '3091877375',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-04-16',
                'alamat'        => 'KP. DURI RT. 004/001 Kel. Semanan Kec.Kalideres Jakarta Barat',
            ],
            [
                'nama'          => 'RADISTI PUTRI',
                'nis'           => '25.01.019',
                'nisn'          => '3081447975',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2008-06-12',
                'alamat'        => 'KP. KALIMATI RT 03 RW 03 Kel.Kedaung Kali Angke Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'Rangga Andrianto',
                'nis'           => '25.01.020',
                'nisn'          => '0078755102',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2007-02-03',
                'alamat'        => 'Kedaung Kaliangke RT 03 RW 08 Kel.Kedaung Kali Angke Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'RASYA PUTRA RAMADHAN',
                'nis'           => '25.01.021',
                'nisn'          => '0092679951',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-09-01',
                'alamat'        => 'KP. PANGAKALAN RT 02 RW 06 Kel. Semanan Kec.Kalideres Jakarta Barat',
            ],
            [
                'nama'          => 'RAVA RIANSYAH MAULANA',
                'nis'           => '25.01.022',
                'nisn'          => '0098862522',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-11-11',
                'alamat'        => 'JL G GALUNGGUNG 12 BLK 13/6 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'RAYHAN OKTAVIO ALGHIFARY',
                'nis'           => '25.01.023',
                'nisn'          => '0093321819',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Banyumas',
                'tanggal_lahir' => '2009-10-16',
                'alamat'        => 'JL. PEDONGKELAN RT 14 RW 13 Kel.Kapuk Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'Rizvan Titannoris Taufik',
                'nis'           => '25.01.024',
                'nisn'          => '0099593266',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-04-24',
                'alamat'        => 'KP. BASMOL NO.20 B RT 15 RW 06 Kel. Kembangan Utara Kec.Kembangan Jakarta Barat',
            ],
            [
                'nama'          => 'SAIDAH LARASATI',
                'nis'           => '25.01.025',
                'nisn'          => '0098405267',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-04-05',
                'alamat'        => 'RUSUNAWA LOKBIN RAWA BUAYA TOWER D LT 7 NO 11 RT 15 RW 01',
            ],
            [
                'nama'          => 'SITI NUR KHOFIFAH',
                'nis'           => '25.01.026',
                'nisn'          => '0094116999',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-03-28',
                'alamat'        => 'JL. MESJID NURUL HUDA RT. 001/001 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'SUMA',
                'nis'           => '25.01.030',
                'nisn'          => '0097582754',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-02-08',
                'alamat'        => 'KAPUK PETERNAKAN III RT 02 RW 07 Kel.Kapuk Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'Vannyansyah',
                'nis'           => '25.01.027',
                'nisn'          => '0101184352',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2010-07-21',
                'alamat'        => 'JL. UKIR RAYA PEDONGKELAN DEPAN RT 02 RW 16 Kel.Kapuk Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'YOGI ARDIANSAH PRATAMA',
                'nis'           => '25.01.028',
                'nisn'          => '0088180790',
                'jenis_kelamin' => 'L',
                'tempat_lahir'  => 'Tangerang',
                'tanggal_lahir' => '2008-03-01',
                'alamat'        => 'KP. KALIMATI RT 14 RW 03 Kel.Kedaung Kali Angke Kec.Cengkareng Jakarta Barat',
            ],
            [
                'nama'          => 'ZAHRA RIZKILLAH',
                'nis'           => '25.01.029',
                'nisn'          => '0097514872',
                'jenis_kelamin' => 'P',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2009-09-15',
                'alamat'        => 'Kp. Utan Bahagia RT 08 RW 05 Kel.Cengkareng timur Kec.Cengkareng Jakarta Barat',
            ],
        ];

        foreach ($siswa as $data) {
            Murid::query()->updateOrCreate(
                [
                    'nis'  => $data['nis'],
                    'nisn' => $data['nisn'],
                ],
                [
                    'kelas_id'      => $kelas->id,
                    'nama'          => $data['nama'],
                    'jenis_kelamin' => $data['jenis_kelamin'],
                    'tempat_lahir'  => $data['tempat_lahir'],
                    'tanggal_lahir' => $data['tanggal_lahir'],
                    'alamat'        => $data['alamat'],
                    'status'        => true,
                ]
            );
        }
    }
}
